# Welcome to Data Analysis with Python
## Welcome to Data Analysis with Python
### python
### django
#### flask
##### Numpy
###### pandas


## Python
- introduction
 - welcome python
      - **hello world**
- data types
   
- data srtuctures
- functions
- files
- regular expressions
- numpy
- pandas

welcome to ~**data analysis** with python workshop in **geethanjali** college~
<img src="python.jpg" width=100px height=100px>

[google](https://www.google.com/)

[Gist](https://gist.edu.in/gist/gist-home/)

## Numpy

- Numpy means Numerical Python
- its works as data manupulating uses mathematical operations and satistical analysis

- creating numpy array

In [1]:
import numpy as np

In [2]:
## creating numpy array
a=np.array([1,2,3,4,5])# single dimentional array

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.size

5

In [6]:
a.shape

(5,)

In [7]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a2.ndim

2

In [9]:
a2.shape

(2, 5)

In [10]:
a3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [11]:
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
# Indexing
a3[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
a3[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [14]:
a3[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [15]:
a3[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [16]:
a3[1:2,2:3]

array([[8]])

In [17]:
a3[1,2]

8

In [18]:
np.random.random()

0.22770874056266033

In [19]:
np.random.randn(1,10)

array([[-0.04726397,  1.0917284 , -1.31503355,  0.82925507, -0.00306904,
        -0.35842859,  0.62780059,  1.25518916, -0.47140191, -0.55323944]])

In [20]:
a=np.random.randint(1,20,10)

In [21]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [22]:
np.random.rand(1,10)

array([[0.70568925, 0.00810178, 0.79621285, 0.54194585, 0.60163081,
        0.07287017, 0.74986236, 0.74309591, 0.15614498, 0.49130693]])

In [23]:
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
a3.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [25]:
a3.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [26]:
a= np.arange(1,11)

In [27]:
a.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [28]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
a2 = np.arange(1,100)

In [31]:
a3=a2[a2%2==0]

In [32]:
a3.size

49

In [33]:
a3.reshape(7,7)

array([[ 2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80, 82, 84],
       [86, 88, 90, 92, 94, 96, 98]])

In [34]:
a3=np.arange(1,31)

In [35]:
a4=a3.reshape(3,10)
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [36]:
a4[0::2,0::2]

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29]])

In [37]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
a1=np.ones([3,5],int)

In [39]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
a3=np.zeros([3,5],int)

In [41]:
a3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
np.vstack((a1,a3))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.hstack((a1,a3))

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [53]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [54]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [55]:
np.linspace(1,50,200)

array([ 1.        ,  1.24623116,  1.49246231,  1.73869347,  1.98492462,
        2.23115578,  2.47738693,  2.72361809,  2.96984925,  3.2160804 ,
        3.46231156,  3.70854271,  3.95477387,  4.20100503,  4.44723618,
        4.69346734,  4.93969849,  5.18592965,  5.4321608 ,  5.67839196,
        5.92462312,  6.17085427,  6.41708543,  6.66331658,  6.90954774,
        7.15577889,  7.40201005,  7.64824121,  7.89447236,  8.14070352,
        8.38693467,  8.63316583,  8.87939698,  9.12562814,  9.3718593 ,
        9.61809045,  9.86432161, 10.11055276, 10.35678392, 10.60301508,
       10.84924623, 11.09547739, 11.34170854, 11.5879397 , 11.83417085,
       12.08040201, 12.32663317, 12.57286432, 12.81909548, 13.06532663,
       13.31155779, 13.55778894, 13.8040201 , 14.05025126, 14.29648241,
       14.54271357, 14.78894472, 15.03517588, 15.28140704, 15.52763819,
       15.77386935, 16.0201005 , 16.26633166, 16.51256281, 16.75879397,
       17.00502513, 17.25125628, 17.49748744, 17.74371859, 17.98

In [57]:
np.full(20,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10])

In [58]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [59]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
a3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [77]:
np.vsplit(a3,3)

[array([[0, 0, 0, 0, 0]]), array([[0, 0, 0, 0, 0]]), array([[0, 0, 0, 0, 0]])]

In [64]:
a4=np.arange(1,31)

In [65]:
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [67]:
a5=a4.reshape(5,6)

In [68]:
a5.sum()

465

In [69]:
a5.mean()

15.5

In [70]:
a5.std()

8.65544144839919

In [71]:
a5.max()

30

In [72]:
a5.min()

1

In [73]:
a5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [74]:
a5.diagonal()

array([ 1,  8, 15, 22, 29])

In [78]:
a5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [79]:
a5.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [80]:
a5.transpose()

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [81]:
np.exp(np.arange(1,10))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [83]:
np.median(a5)

15.5

In [85]:
np.percentile(a5,25)

8.25

In [86]:
np.sin(a5)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
        -0.53657292],
       [ 0.42016704,  0.99060736,  0.65028784, -0.28790332, -0.96139749,
        -0.75098725],
       [ 0.14987721,  0.91294525,  0.83665564, -0.00885131, -0.8462204 ,
        -0.90557836],
       [-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
        -0.98803162]])

In [87]:
np.tan(a5)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00, -2.91006191e-01],
       [ 8.71447983e-01, -6.79971146e+00, -4.52315659e-01,
         6.48360827e-01, -2.25950846e+02, -6.35859929e-01],
       [ 4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01,  3.49391565e+00, -1.13731371e+00],
       [ 1.51589471e-01,  2.23716094e+00, -1.52749853e+00,
         8.85165604e-03,  1.58815308e+00, -2.13489670e+00],
       [-1.33526407e-01,  1.17875355e+00, -3.27370380e+00,
        -2.81429605e-01,  8.87142844e-01, -6.40533120e+00]])